/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/item/AppFooter.vue')['default']
    AppPlayer: typeof import('./src/components/player/AppPlayer.vue')['default']
    Icons: typeof import('./src/components/home/Icons.vue')['default']
    ItemList: typeof import('./src/components/item/ItemList.vue')['default']
    JukeBox: typeof import('./src/components/player/JukeBox.vue')['default']
    MusicItem: typeof import('./src/components/item/MusicItem.vue')['default']
    MusicList: typeof import('./src/components/home/MusicList.vue')['default']
    MusicPlayer: typeof import('./src/components/item/MusicPlayer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowIcons: typeof import('./src/components/player/ShowIcons.vue')['default']
    SwiperTop: typeof import('./src/components/home/SwiperTop.vue')['default']
    TopNav: typeof import('./src/components/home/TopNav.vue')['default']
    TopTtile: typeof import('./src/components/player/TopTtile.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}
